google/alioth

alioth-cli/src/main.rs
alioth/src/virtio/dev/net/net.rs

The current virtio-net implementation assumes the tap device path is referring to a macvtap or ipvtap. This commit allows using a tun/tap interface pre-created by `ip tuntap add mode tap $IF_NAME` as a backend.
Usage:
```
--net if=$IF_NAME,mac=$IF_MAC,mtu=$IF_MTU
```

feat(net): use a tun/tap interface as a backend

---

alioth/src/virtio/dev/net/net.rs

This gives us the backward compatibility for command line options like `--net if=test-tap,mac=aa:bb:cc:dd:ee:ff,mtu=1500`.
Fixes: 6a66b2d29970 ("feat(cli)!: use serde-aco to parse cli options")

fix(net): add alias and default to param fields

---

alioth-cli/src/main.rs
alioth/src/arch/x86_64/sev.rs
alioth/src/board/board.rs
alioth/src/board/x86_64.rs
alioth/src/hv/hv.rs
alioth/src/hv/kvm/bindings.rs
alioth/src/hv/kvm/ioctls.rs
alioth/src/hv/kvm/kvm.rs
alioth/src/hv/kvm/sev/bindings.rs
alioth/src/hv/kvm/sev/sev.rs
alioth/src/hv/kvm/vcpu/vcpu.rs
alioth/src/hv/kvm/vm.rs
alioth/src/loader/firmware/x86_64.rs
alioth/src/mem/mapped.rs
alioth/src/utils/ioctls.rs
alioth/src/virtio/virtio.rs
alioth/src/vm.rs
docs/coco.md

Alioth supports booting confidential guests on the following platforms:
- AMD-SEV [^sev]
WARNING: the current implementation takes QEMU [^qemu] as a reference and should
be used in testing environments only.
To launch an SEV guest,
1. build the stage0 firmware from the Oak project[^stage0],
2. prepare the guest Linux kernel of ELF format, the initramfs, and the kernel
command line in a text file,
3. for SEV guests, `POLICY=0x1`, for SEV-ES guests, `POLICY=0x5`,
4. launch the guest by
```bash
./alioth run -f /path/to/oak_stage0.bin \
--mem-size 1G \
--num-cpu 2 \
--fw-cfg name=opt/stage0/elf_kernel,file=/path/to/elf_kernel \
--fw-cfg name=opt/stage0/initramfs,file=/path/to/initramfs \
--fw-cfg name=opt/stage0/cmdline,file=/path/to/cmdline.txt \
--coco sev,policy=$POLICY
```
[^sev]:
[AMD …

Boot AMD-SEV guests with Oak/Stage0

---

alioth-cli/src/main.rs
alioth/src/device/fw_cfg/fw_cfg.rs
alioth/src/vm.rs

Add kernel, initramfs, and cmdline to the FwCfg device when a firmware image is provided at the same time. This enables Alioth to boot SEV enabled guests with a compressed bzImage file.

feat(sev): boot Oak/Stage0 with Linux bzImage

---

alioth/src/hv/hv.rs
alioth/src/hv/kvm/ioctls.rs
alioth/src/hv/kvm/kvm.rs
alioth/src/hv/kvm/vm.rs
alioth/src/mem/mem.rs
alioth/src/virtio/dev/dev.rs
alioth/src/virtio/pci.rs
alioth/src/virtio/virtio.rs
alioth/src/vm.rs

KVM_IOEVENTFD avoids the VM exits of VCPU threads from kernel space
to user space.
Further we use a non-zero notify_off_multiplier [^1] in virtio device
configs. By just looking at the MMIO address we are able to tell
which queue is sending the notification. The value written to the
MMIO address is not needed. Thus the instruction decoding in the KVM
is avoided.
Test setup:
- Host CPU: AMD Ryzen 9 5950X
- VM: memory size 1G, 1 VCPU
virtio-net thought put by iperf3:
- VM -> host
- without KVM_IOEVENTFD: 30.6 Gbits/sec
- with KVM_IOEVENTFD: 33.5 Gbits/sec
- Host -> VM
- without KVM_IOEVENTFD: 19.5 Gbits/sec
- with KVM_IOEVENTFD: 25.4 Gbits/sec
[^1]: Virtio Spec 1.2, Sec 4.1.4.4.

perf(virtio)!: use KVM_IOEVENTFD for queue notify

---

alioth/src/virtio/dev/blk.rs
alioth/src/virtio/dev/dev.rs
alioth/src/virtio/dev/entropy.rs
alioth/src/virtio/dev/net/net.rs
alioth/src/virtio/virtio.rs

Previously, each device only returns the device specific features and VirtioDevice::new() adds the general virtio feature bits. This causes troubles for supporting vhost-user backends, which may implement a different set of general virtio feature bits.
This commit lets individual devices return the full feature sets. The general virtio feature bits implemented by the module virtio is moved to `FEATURE_BUILT_IN`, which implicitly turns on the `EVENT_IDX` for the entropy and block device.

fix(virtio): devices return the full feature sets

---

alioth-cli/src/main.rs
alioth/src/board/board.rs
alioth/src/board/x86_64.rs
alioth/src/hv/hv.rs
alioth/src/hv/kvm/bindings.rs
alioth/src/hv/kvm/ioctls.rs
alioth/src/hv/kvm/kvm.rs
alioth/src/hv/kvm/vm.rs
alioth/src/loader/firmware/x86_64.rs
alioth/src/mem/mapped.rs
alioth/src/pci/cap.rs
alioth/src/virtio/dev/blk.rs
alioth/src/virtio/dev/dev.rs
alioth/src/virtio/dev/entropy.rs
alioth/src/virtio/dev/fs.rs
alioth/src/virtio/dev/net/net.rs
alioth/src/virtio/pci.rs
alioth/src/virtio/virtio.rs
alioth/src/virtio/vu.rs

A host directory can be shared with the guest by
1. virtiofsd[^1] flag: `--shared-dir /path/to/dir --socket-path /tmp/virtiofsd`
2. Alioth flag: `--fs vu,socket=/tmp/virtiofsd,tag=host-dir`
[^1]: https://gitlab.com/virtio-fs/virtiofsd

Support vhost-user virtio-fs with virtiofsd as the backend

---

alioth/src/virtio/dev/fs.rs

Fixed: 359ab26fb216f ("feat(fs): support virtio-fs DAX mapping")

fix(fs): deregister the backend channel upon reset

---

README.md

/dev/vsock is the guest vsock driver.
Fixes: 2e59fe08666d ("docs: update README.md")

docs: fix the vhost-vsock dev path

---

alioth/src/board/board.rs
alioth/src/pci/bus.rs
alioth/src/pci/pci.rs
alioth/src/pci/segment.rs
alioth/src/vm.rs

MSI on aarch64 requires an additional devid, which is usually the device BDF. Thus the `MsiSender` of a PCI device needs to know the BDF. However, currently the BDF is unknown until the device has been plugged into the PCI bus.
This commit changes the API such that a BDF is reserved first before a device is plugged in. The reserved BDF then can be passed to the constructor of an `MsiSender`.

feat(pci)!: reserve a BDF before adding a device

---

alioth/src/hv/kvm/bindings.rs
alioth/src/hv/kvm/vm/vm.rs

Fixes: 6ca2e25b89f9 ("feat(kvm/aarch64)!: assign a DevID to MsiSender")

fix(kvm/aarch64): set DevID in GSI routing table

---

alioth/src/device/fw_cfg/fw_cfg.rs
alioth/src/device/pl011.rs
alioth/src/device/pvpanic.rs
alioth/src/device/serial.rs
alioth/src/mem/emulated.rs
alioth/src/mem/mem.rs
alioth/src/pci/bus.rs
alioth/src/pci/cap.rs
alioth/src/pci/config.rs
alioth/src/pci/segment.rs
alioth/src/virtio/dev/entropy.rs
alioth/src/virtio/pci.rs

Conceptually the side effect of MMIO write is not an Error.
All `Action`s should be handled internally.

fix(mem)!: wrap `Action` in `Ok` instead of `Err`

---

alioth/src/board/aarch64.rs
alioth/src/board/board.rs
alioth/src/board/x86_64.rs
alioth/src/loader/firmware/x86_64.rs
alioth/src/mem/addressable.rs
alioth/src/mem/mem.rs
alioth/src/pci/config.rs
alioth/src/vm.rs

It turns out ad-hoc address allocation is a bad idea.

fix(mem)!: remove legacy address allocation APIs

---

.github/workflows/rust.yml

- if the cached toolchain has nightly rust, just use it,
- install a new nightly rust if there is a new stable rust.

ci: avoid nightly rust being installed every time

---

alioth/src/board/board.rs
alioth/src/mem/emulated.rs
alioth/src/pci/cap.rs
alioth/src/pci/config.rs
alioth/src/virtio/pci.rs

Without the fix, after a reboot, while PCI device resources have been removed from the memory bus, the config space Command register may still have the MEM and IO bit on.
Fixes: bc5ee80a77ce ("fix(pci): do not add resources to memory at boot")

fix(board)!: reset PCI device config space

---

alioth/src/mem/mapped.rs
alioth/src/virtio/dev/fs.rs

Vhost user backends need mmap offsets to set up correct mappings.

fix(mem): save the offset of an mmap-ed file

---

Cargo.lock
Cargo.toml
alioth-cli/src/main.rs
alioth/Cargo.toml
alioth/src/arch/x86_64/sev.rs
alioth/src/device/fw_cfg/fw_cfg.rs
alioth/src/hv/hv.rs
alioth/src/hv/kvm/kvm.rs
alioth/src/mem/mem.rs
alioth/src/net/net.rs
alioth/src/vfio/vfio.rs
alioth/src/virtio/dev/blk.rs
alioth/src/virtio/dev/fs.rs
alioth/src/virtio/dev/net/net.rs
alioth/src/virtio/dev/vsock/vhost_vsock.rs
serde-aco-derive/Cargo.toml
serde-aco-derive/src/help.rs
serde-aco-derive/src/lib.rs
serde-aco/Cargo.toml
serde-aco/src/help.rs
serde-aco/src/lib.rs

Trait `Help` returns a description of a type. It is used to generate the help message for the command line interface.
The derive macro implements `Help` for enums and structs and includes inline documentation in the description.
`help_text` generates the help message at runtime. It cannot be done at compile time because proc macro cannot access the information of sub-field types.
Now `alioth run --help` gives help message for flags, for example:
```text
-m, --memory <MEMORY>      Specify the memory of the guest.
* size=<integer>,backend=<MemBackend>,shared=<bool>,thp=<bool>
- size           Total guest memory size in bytes. [default: 1G]
- backend        Host backend, [default: anon]
- shared         mmap() guest memory with MAP_SHARED or MAP_PRIVATE.
[default: false]
- thp …
```

Add help messages to command line interface

---

alioth-cli/src/main.rs

Fixes: 6381397d5657 ("doc(cli): add help message to the flag --object")

doc(cli): fix the example in `--object` help

---

serde-aco/src/de.rs
serde-aco/src/error.rs

If an id is not found, it is more likely to be a typo than a value which is serialized to `id_xxxx`. If the later case really happens, the value can still be represented by the id_ syntax.

fix(aco)!: report an error if an id is not found

---

alioth/src/hv/kvm/vmexit.rs

1u64.wrapping_shl(64) returns 1 instead of 0. Without the fix, for 64bit MMIO, the mask is 0 instead of u64::MAX.
Fixes: c988169b2758 ("fix(kvm): clear the high part of mmio write values")

fix(kvm): calculate correct mask for 64bit MMIO

---

alioth/src/virtio/dev/net/net.rs

This reverts commit f365429dffafaefb29cf668e9188cb28a6b16142.
It causes 100% CPU usage.

Revert "perf(net): deregister tap from poll while handling events"

---

alioth/src/virtio/dev/dev.rs
alioth/src/virtio/worker/io_uring.rs
alioth/src/virtio/worker/mio.rs

This reverts commit 0c4fc4e3ba8e12752d6652810029e5bb4ab6bc97.
It causes 100% CPU usage while io_uring is enabled.

Revert "fix(virtio): monitor eventfds with IORING_OP_POLL_ADD"

---

alioth/src/virtio/dev/dev.rs
alioth/src/virtio/worker/io_uring.rs
alioth/src/virtio/worker/mio.rs

With `IORING_POLL_ADD_MULTI`, we do not need to re-add the waker to the ring.
Commit 0c4fc4e3ba8e also used IORING_OP_POLL_ADD for ioeventfds, which was problematic because POLL_ADD does not clear the internal counter of an eventfd when it creates a cqe. So once an ioeventfd is re-added to the ring, it immediately generates a new cqe, despite that there is no new MMIO yet. This causes the event loop thread to spin.

fix(virtio): monitor the waker with IORING_OP_POLL_ADD

---

alioth/src/virtio/dev/fs/vu.rs

Fixes: cb797a6aeaaf ("refactor(vu): split VuDev into VuSession and VuChannel")

fix(fs): read payload after header is received

---

alioth/src/virtio/queue/queue.rs
alioth/src/virtio/queue/queue_test.rs

Ok(0) from read() or write() generally means either the provided buffer is empty, or there are no more data to be provided or accepted by the file descriptor. The second case should be treated as WouldBlock.

fix(virtio): do not treat Ok(0) as errors
